apiVersion: apps/v1
kind: Deployment
metadata:
  name: todotaskui-deployment
  labels:
    app: todotaskui
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todotaskui
  template:
    metadata:
      labels:
        app: todotaskui
    spec:
      containers:
      - name: todotaskui
        image: <docker-register>/todotaskui:latest # Replace with the correct image tag
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: todotaskui-service
  labels:
    app: todotaskui
spec:
  selector:
    app: todotaskui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todotaskui-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: yourdomain.com # Replace with your actual domain in aws or other cloud
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: todotaskui-service
            port:
              number: 80